import type { Metadata } from "next";

import "./css/fonts.css";
import "./css/main.css";
import "./css/utilities.css";
import "focus-visible";

import NextThemeProvider from "@/providers/theme-provider";

//import { Header } from '@/components/Header'
//import { Description, OgDescription, OgTitle, Title } from '@/components/Meta'
import Head from "next/head";
//import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const FAVICON_VERSION = 3;

function v(href: string) {
  return `${href}?v=${FAVICON_VERSION}`;
}

//      <Script src="/scripts/theme.js" strategy="beforeInteractive" />

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="dark [--scroll-mt:9.875rem] lg:[--scroll-mt:6.3125rem] [scrollbar-gutter:stable]"
    >
      <Head>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href={v("/favicons/apple-touch-icon.png")}
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href={v("/favicons/favicon-32x32.png")}
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href={v("/favicons/favicon-16x16.png")}
        />
        <link rel="manifest" href={v("/favicons/site.webmanifest")} />
        <link
          rel="mask-icon"
          href={v("/favicons/safari-pinned-tab.svg")}
          color="#38bdf8"
        />
        <link rel="shortcut icon" href={v("/favicons/favicon.ico")} />
        <meta name="apple-mobile-web-app-title" content="Tailwind CSS" />
        <meta name="application-name" content="Tailwind CSS" />
        <meta name="msapplication-TileColor" content="#38bdf8" />
        <meta
          name="msapplication-config"
          content={v("/favicons/browserconfig.xml")}
        />
        <meta name="theme-color" content="#f8fafc" />
      </Head>

      <body className="antialiased text-slate-500 dark:text-slate-400 bg-white dark:bg-slate-900">
        <NextThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          {children}
        </NextThemeProvider>
      </body>
    </html>
  );
}
